services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app-network

  roiinovators:
    build: .
    container_name: roiinovators
    restart: unless-stopped
    networks:
      - app-network
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: container/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--interval", "30", "--cleanup", "--rolling-restart", "--label-enable"]

networks:
  app-network:
    driver: bridge
